name = "snowpeak"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["rami3l"]
maintainers = ["rami3l <rami3l@outlook.com>"]
maintainers-logins = ["rami3l"]

executables = ["main"]

[[depends-on]]
gnat = ">=12.1"

[build-switches]
"*".ada_version = "GNAT_Extensions"

[[actions]]
type = "pre-build"
command = ["make", "generate", "expand"]
