name = "snowpeak"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["rami3l"]
maintainers = ["rami3l <rami3l@outlook.com>"]
maintainers-logins = ["rami3l"]

executables = ["main"]

[build-switches]
"*".ada_version = "Ada2022"
